# Generated by Django 4.0.3 on 2022-06-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('direction', models.CharField(max_length=5)),
                ('door', models.CharField(max_length=50)),
            ],
        ),
    ]
