# Generated by Django 4.0.3 on 2022-06-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('direction', models.CharField(max_length=50)),
                ('door', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_Employee',
        ),
    ]
