# Generated by Django 4.0.3 on 2022-06-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uploader', '0002_acs_delete_tbl_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acs',
            name='direction',
            field=models.CharField(max_length=5),
        ),
    ]
