# Generated by Django 4.0.3 on 2022-06-13 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uploader', '0004_employee_remove_acs_employee_acs_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acs',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
