# Generated by Django 4.0.3 on 2022-06-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uploader', '0005_rename_employee_id_acs_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
