# Generated by Django 4.0.3 on 2022-06-15 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uploader', '0006_uploadexcel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadExcel',
        ),
    ]
